### ISSUE TITLE
How does it compare to AssemblyPublicizer?

### ISSUE THREAD

**Issue by colinfang** [rwmt/Publicise#2]
Sorry if it is not the right place to ask this question.

I recently came across the concept of Publicizer which is soooo cool.  

Do you happen to know https://github.com/CabbageCrow/AssemblyPublicizer  and what is the main difference from this repo and AssemblyPublicizer?

**Comment by notfood** [comment]
We use https://github.com/krafs/Publicizer/ so this one is deprecated.
